const CLASS_ICON_MAP: Record<string, string> = {
  Workspace: "project",
  Players: "organization",
  Lighting: "lightbulb",
  ReplicatedFirst: "run",
  ReplicatedStorage: "package",
  ServerScriptService: "server-process",
  ServerStorage: "archive",
  StarterGui: "device-mobile",
  StarterPack: "briefcase",
  StarterPlayer: "account",
  Teams: "group-by-ref-type",
  SoundService: "unmute",
  Folder: "folder",
  Model: "folder-library",
  Script: "file-code",
  LocalScript: "file-code",
  ModuleScript: "file-code",
  Part: "symbol-object",
  MeshPart: "symbol-object",
  UnionOperation: "symbol-object",
  FolderMesh: "symbol-object",
  Attachment: "symbol-event",
  WeldConstraint: "plug",
  Motor6D: "plug",
  Constraint: "plug",
  RemoteEvent: "radio-tower",
  RemoteFunction: "radio-tower",
  BindableEvent: "broadcast",
  BindableFunction: "broadcast",
  ScreenGui: "browser",
  SurfaceGui: "browser",
  BillboardGui: "browser",
  Frame: "layout",
  TextLabel: "symbol-string",
  TextButton: "symbol-string",
  ImageLabel: "symbol-color",
  ImageButton: "symbol-color",
  ViewportFrame: "device-camera-video",
  Camera: "device-camera-video",
  Animation: "play-circle",
  Sound: "unmute",
  ParticleEmitter: "sparkle",
  Trail: "sparkle",
  Beam: "sparkle",
  Configuration: "settings-gear",
  NumberValue: "symbol-number",
  StringValue: "symbol-string",
  BoolValue: "symbol-boolean",
  IntValue: "symbol-number",
  ObjectValue: "references",
  CFrameValue: "symbol-misc",
  Vector3Value: "symbol-array",
  Color3Value: "symbol-color",
  UIStroke: "symbol-color",
};

export function iconIdForClass(className: string, hasChildren: boolean): string {
  return CLASS_ICON_MAP[className] ?? (hasChildren ? "folder" : "symbol-field");
}
